apiVersion: v2
name: gravity-ci-cd-agent
description: Helm chart to deploy the Gravity Cloud CI/CD Agent for ArgoCD
type: application
icon: https://gravitycloud.ai/favicon.png
appVersion: 1.0.20
version: 1.0.27
maintainers:
  - name: Vatsal Bajpai
    email: vatsal@gravitycloud.ai